### ISSUE TITLE
List of issues where there is no programmatic way to create data in the tenant

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#845]
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/322
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/511
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/577
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/607
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/621
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/624
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/638
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/651
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/745
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/747
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/754
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/779
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/792
- [ ] https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/827
